fr:
  languageName: Français
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Stras'Bêrgerie. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Stras'Bêrgerie"
  params:
    description: "Site Description"
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Nous soutenir"
      link: "/nous-soutenir/"
    # footer_cta:
    # Call to action à la droite du pied de page
    #   text: "Join us"
    #   link: "/example-page/"
    # github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "Presentation"
      name: "Présentation"
      url: "/presentation/"
      weight: 1
      # Sous menu pour ex
    # - identifier: "Actualites"
    #   name: "Example Child Page"
    #   url: "/example-page/"
    #   weight: 1
    #   post: "Nulla consequat massa quis enim. Donec pede justo."
    #   parent: "about"
    - identifier: "actualites"
      name: "Actualités"
      url: "/actualites/"
      weight: 2

