######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/logo-SB.png"
logo_on_black: "/img/logo-SB.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: ""
  show_edit_link: false

social_links:
  devstats: ""
  discord: ""
  facebook: "https://www.facebook.com/people/Strasb%C3%AArgerie/61576637516412/"
  flickr: ""
  github: ""
  instagram: "https://www.instagram.com/strasbergerie?igsh=MTB2ajdtN3RsM2E4aw=="
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
